name: Gravewarden
version: '${version}'
main: dev.znxki.gravewarden.Gravewarden
api-version: '1.20'
authors: [ zNxki_ ]
description: Gravewarden protects player items by creating a gravestone on death.
