name: Gravewarden
version: '${version}'
main: dev.znxki.gravewarden.Gravewarden
api-version: '1.20'
authors: [ zNxki_ ]
description: Gravewarden protects player items by creating a gravestone on death.
commands:
  gravewarden:
    description: Main command for Gravewarden.
    aliases: [ grave ]

permissions:
  gravewarden.*:
    children:
      - gravewarden.admin
      - gravewarden.list
      - gravewarden.list.others
      - gravewarden.remove
      - gravewarden.remove.all
      - gravewarden.teleport

  gravewarden.admin: { }

  gravewarden.teleport: { }

  gravewarden.remove: { }
  gravewarden.remove.all:
    children:
      - grave.remove

  gravewarden.list: { }
  gravewarden.list.others:
    children:
      - grave.list